# Generated by Django 2.2.4 on 2019-11-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uplaod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_Main_Img',
            field=models.FileField(upload_to='media/'),
        ),
    ]
