# Generated by Django 2.2.4 on 2019-11-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uplaod', '0002_auto_20191106_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='Upload_File',
        ),
    ]
