# Generated by Django 2.2.4 on 2019-11-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uplaod', '0003_auto_20191108_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='Upload_File',
            new_name='upload_file',
        ),
    ]
