# Generated by Django 2.2.4 on 2019-11-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uplaod', '0004_auto_20191108_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
    ]
