# Generated by Django 2.2.4 on 2019-11-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uplaod', '0005_remove_hotel_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='WhatsApp',
        ),
    ]
